version: '3.9'
services:
  nginx: 
    restart: unless-stopped
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/development/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on: 
      - core_app
  core_app:
    container_name: core_app
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate && 
          gunicorn djangoGithubActions.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis  
  redis:
    image: 'redis:6.2.11-alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning  
    hostname: redis    
    volumes:
      - redisdata:/data

  celery:
    build: .
    container_name: celery
    command: celery --app=djangoGithubActions worker --loglevel=info --logfile=logs/celery.log
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - core_app
      - redis   
    volumes:
      - celery:/celerydata   

  worker_1:
    build: .
    container_name: worker1
    restart: always
    command: celery --app=djangoGithubActions worker --loglevel=info --logfile=logs/celery.log
    depends_on:
      - redis
      - core_app
      - celery
    


  dashboard:
    build: .
    container_name: dashboard
    command: celery flower -A djangoGithubActions --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - core_app
      - redis
      - celery    
volumes:
  static_volume:
  media_volume:
  redisdata:
  celery:
