version: '3.9'

services:
  nginx: 
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/production/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/production:/etc/nginx/conf.d
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on: 
      - api
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       
  api:
    container_name: core_app
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate &&
          gunicorn djangoGithubActions.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media   
    depends_on:
      - redis     
  redis:
    image: 'redis:6.2.11-alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning  
    hostname: redis    
    volumes:
      - redisdata:/data      

volumes:
  static_volume:
  media_volume:
  redisdata: