version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./docker/nginx/development/Dockerfile
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
      
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on: 
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate &&
          gunicorn djangoGithubActions.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: