kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-new-pv-volume
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-new-pv-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
